### ISSUE TITLE
Change GISTY_ACCESS_TOKEN value

### ISSUE THREAD

**Issue by MartinDelille** [swdyh/gisty#19]
I have published my GISTY_ACCESS_TOKEN value and I would like to change it for security reason. How can I do that?

**Comment by swdyh** [comment]
You can revoke gisty access token from here.
https://github.com/settings/applications

And, You can generate new token .
"Personal access tokens" -> "Generate new token"

**Comment by MartinDelille** [comment]
Awesome! Sorry for the annoyance :-)
